name: Sammy Duggasani
title: sduggasani.github.io
description: >-
  Photography
email: sduggasani@college.harvard.edu
default_img: https://static.christopheradams.io/file/cxadams-website/medium/nextcloud/Photos/Albums/2022/20220522-1235_Taipei_TaipeiDangdai/20220522-1235_Taipei_TaipeiDangdai_L1000274-0.jpg
location: Atlanta
newsletter: https://christopheradams.us4.list-manage.com/subscribe?u=acc7f3d8b7e235071d274920b&id=1c61d44635
timezone: ETC/UTC

url: https://sduggasani.github.io
baseurl: ""

source_url: "https://github.com/christopheradams/christopheradams.io/blob/master/"

social:
  - name: X
    url: https://x.com/sduggasani
  - name: instagram
    url: https://www.instagram.com/sammy_duggasani
  - name: github
    url: https://github.com/sduggasani
  # - name: flickr
  #   url: https://flickr.com/photos/christopheradams
  # - name: hicetnunc
  #   url: https://www.hicetnunc.xyz/christopheradams

# Authors
# see _data/authors.yml
author:
  name: Sammy Duggasani
  email: sduggasani@college.harvard.edu
  uri: https://sduggasani.github.io

# Collections
collections:
  topics:
    output: true
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      permalink: /posts/:year/:month/:day/:title/
      author: sduggasani
  - scope:
      path: ""
      type: topics
    values:
      layout: category
      permalink: /categories/:title/
      author: sduggasani

paginate: 12
paginate_path: "/page/:num/"

feed:
  posts_limit: 25

excerpt_separator: <!--more-->

sass:
  sass_dir: _scss
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
exclude:
  - CNAME
  - LICENSE
  - README.md
  - package-lock.json
  - package.json
  - screenshot.png
